server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

spring:
  cloud:
    config:
      server:
        bootstrap: true
        native:
          searchLocations: file:///D:/workspace/configprop/
  profiles:
    active: native
  application:
    name: config

welcome:
  message: DOWN!
